In [12]:
import pandas as pd
import zipfile

zip_path = "../rfi_data/transitions_parsed.zip"

# Extract and read the zipped CSV
with zipfile.ZipFile(zip_path) as z:
    print(z.namelist())  # List files in the zip to confirm the name
    with z.open("transitions_parsed.csv") as f:
        transitions = pd.read_csv(f, index_col=0)

transitions.shape
transitions

['transitions_parsed.csv']

           Species   Line  Frequency (MHz)
Transition
H253alpha        H   H253       403.680888
He253alpha      He  He253       403.845270
C253alpha        C   C253       403.882156
H252alpha        H   H252       408.496141
He252alpha      He  He252       408.662485
...            ...    ...              ...
He161alpha      He  He161      1561.838982
C161alpha        C   C161      1561.981635
H160alpha        H   H160      1590.567189
He160alpha      He  He160      1591.214882
C160alpha        C   C160      1591.360219

[282 rows x 3 columns]

In [13]:
transitions[50:80]

           Species   Line  Frequency (MHz)
Transition
C237alpha        C   C237       491.131948
H236alpha        H   H236       497.140503
He236alpha      He  He236       497.342943
C236alpha        C   C236       497.388369
H235alpha        H   H235       503.500471
He235alpha      He  He235       503.705501
C235alpha        C   C235       503.751508
H234alpha        H   H234       509.969388
He234alpha      He  He234       510.177053
C234alpha        C   C234       510.223650
H233alpha        H   H233       516.549598
He233alpha      He  He233       516.759942
C233alpha        C   C233       516.807141
H232alpha        H   H232       523.243504
He232alpha      He  He232       523.456574
C232alpha        C   C232       523.504384
H231alpha        H   H231       530.053572
He231alpha      He  He231       530.269415
C231alpha        C   C231       530.317848
H230alpha        H   H230       536.982334
He230alpha      He  He230       537.200998
C230alpha        C   C230       537.250064
H229alpha        H   H229       544.032385
He229alpha      He  He229       544.253920
C229alpha        C   C229       544.303631
H228alpha        H   H228       551.206393
He228alpha      He  He228       551.430849
C228alpha        C   C228       551.481215
H227alpha        H   H227       558.507093
He227alpha      He  He227       558.734522

In [ ]:
# Enable autoreload of modules
%load_ext autoreload
%autoreload 2

# Now import your function
from RFI.helpers import load_demo_data

# Use it
data = load_demo_data()
print(data.shape)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
(21, 200)

AttributeError: 'memmap' object has no attribute 'head'